"use client"

//notes about this file
//This file was written mostly by GPT-5 mini with some parts written by Daniel Briggs

import React, { useEffect, useRef, useState } from "react";
import { Header } from "@/components/layout";
import PdfReadableLine from "@/components/pdf-reading/PdfReadableLine";
import PdfImageLine from "@/components/pdf-reading/PdfImageLine";
import { Readability } from "@mozilla/readability";
import { getResolvedPDFJS, extractText, getDocumentProxy, extractImages } from 'unpdf';
import type { TextItem, TextContent } from 'pdfjs-dist/types/src/display/api';



export default function Page() {
  const [file, setFile] = useState<File | null>(null);
  const [fileName, setFileName] = useState<string | null>(null);
  const [readableHtml, setReadableHtml] = useState<React.ReactNode | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const mounted = useRef(true);




  //USER SETTINGS

  const defaultSettings = {
    "AIDefaultShortening": false,
    "AIFullDocumentSummary": false,
    "displayPageNumbers": true,
    "backgroundColor": "#FFFFFF",
    "textColor": "#000000",
    "minLengthToSummarize": 200,
    "targetSummaryLength": 60, //percentage
  };

  type PDFReaderSettings = typeof defaultSettings;
  
  //this function written using Copilot inline suggestions then edited
  function getsettings() {
    
    try {
      const localStorageSettings = localStorage.getItem("pdfReaderSettings");
      if (localStorageSettings) {
        return JSON.parse(localStorageSettings) as PDFReaderSettings;
      }
      else {
        throw new Error("no settings in local storage")
      }
    }
    catch {
      return defaultSettings;
    }
  }

  let settings = getsettings()
 


  useEffect(() => {
    mounted.current = true;
    return () => {
      mounted.current = false;
    };
  }, []);

  async function handleFileChange(e: React.ChangeEvent<HTMLInputElement>) {
    const f = e.target.files?.[0] ?? null;
    if (!f) return;
    const isPdf = f.type === "application/pdf" || f.name.toLowerCase().endsWith(".pdf");
    if (!isPdf) {
      alert("Please upload a PDF file.");
      e.currentTarget.value = "";
      setFile(null);
      setFileName(null);
      return;
    }
    setFile(f);
    setFileName(f.name);
    setReadableHtml(null);
    setError(null);
  }

  useEffect(() => {
    if (!file) return;
    let cancelled = false;

    async function processPdf() {
      setLoading(true);
      setError(null);


      try {
       
        
        if (file == null) throw new Error("No file to process");
        const arrayBuffer = await file.arrayBuffer();




        const pdf = await getDocumentProxy(new Uint8Array(arrayBuffer));
        console.log(await pdf.numPages);
        const pdfJS = await getResolvedPDFJS(); //get direct access to the underlying PDF.js library used by unpdf
        
        //load list of all pages
        let listOfPagePromises = [];
        for (let i = 1; i <= pdf.numPages; i++) {
          listOfPagePromises.push(pdf.getPage(i));
        }
        const pages = await Promise.all(listOfPagePromises);
        

        //for each page extract the textContent elements
        let textContents : TextItem[][] = [];
        
        for (let page of pages) {
          const textContent : TextContent = await page.getTextContent({includeMarkedContent: false}); //get the list of TextContent objects without any TextMarkedContentObjects
          let textContentItems = textContent.items as TextItem[];
          textContents.push(textContentItems); //store each page's text items in its own array
        }

        //collect page heights from PDF.js page viewports (scale 1)
        const pageHeights: number[] = pages.map((page) => page.getViewport({ scale: 1 }).height);

        //build a list containing all the text and images from the pdf with the relative text sizes
        type DocText = { type: 'text'; text: string; headingLevel: number; yPos: number };
        type DocImage = { type: 'image'; src: string; yPos: number };
        type DocElement = DocText | DocImage;

        let docElements: DocElement[] = [];

        //create a list of all the text heights in the document to sort by
        let heights : number[] = [];
        for (let pageItems of textContents) {
          for (let item of pageItems) {
            if (!heights.includes(item.height)) {
              heights.push(item.height);
            }
          }
        }
        heights.sort((a,b) => b-a); //sort heights from largest to smallest

        //The following conversion from heights to headings was generated by GPT-5 mini
        // Create a dictionary mapping each unique height to an estimated heading level (1..6)
        // Largest height -> 1 (h1), smallest -> 6 (h6). Heights in between are scaled.
        const heightToHeading: Record<number, number> = {};
        if (heights.length === 1) {
          heightToHeading[heights[0]] = 1;
        } else if (heights.length > 1) {
          const maxIndex = heights.length - 1;
          for (let i = 0; i < heights.length; i++) {
            const rank = i; // 0 = largest, maxIndex = smallest
            const level = Math.min(6, Math.max(1, Math.round((rank / maxIndex) * 5) + 1));
            heightToHeading[heights[i]] = level;
          }
        }
        

        let lastXIndent = -999;
        //populate docElements with text items (with position tracking)
        let tempDocText: { text: string; headingLevel: number; yPos: number }[] = [];
        let pageStartYPos = 0; //track the yPos of the start of each page
        
        for (let pageNum = 0; pageNum < textContents.length; pageNum++) {
          const pageItems = textContents[pageNum];
          const pageHeight = pageHeights[pageNum];
          
          //update pageStartYPos for the current page
          if (pageNum > 0) {
            pageStartYPos += pageHeights[pageNum - 1];
          }
          
          let lastLineWasPageNumber = false;
          for (let i = 0; i < pageItems.length; i++) {
            const item = pageItems[i] as TextItem;
            let lineText = item.str;


            //if the text is empty or only whitespace, skip it
            if (lineText.trim() === "") continue;
            

            //check whether this is a new page (first item of this page)
            let newPage = (i == 0);

            //check the heading level
            const headingLevel = heightToHeading[item.height] || 6; //default to 6 if height not recognized
            

            //if it's a new page then check whether this line or the last line is likely a page number and reformat it
            if (newPage) {
              
              //check whether the lineText is a arabic or roman numeral
              let pageNumberInDocument = Number(lineText.trim());
              if (isNaN(pageNumberInDocument)) {
                //try parsing as a roman numeral
                pageNumberInDocument = parseRomanNumeral(lineText.trim());
                if (isNaN(pageNumberInDocument)) {
                  //probably not a page num
                }
              }

              //if the lineText is likely a page number, reformat it to "Page X"
              if (!isNaN(pageNumberInDocument)) {
                lineText = "Page " + pageNumberInDocument;
                
                
                if (settings.displayPageNumbers) {
                  lastLineWasPageNumber = true //so that the next line gets set as a new paragraph
                  const adjustedYPos = calculateAdjustedYPos(pageHeight, item.transform[5], pageStartYPos) 
                  tempDocText.push({"text": lineText, "headingLevel": headingLevel, "yPos": adjustedYPos});
                  
                }
                continue; //skip the other parsing logic for this line
              }
            }

            //check whether this is the start of a new paragraph
            let isNewParagraph = false;
            if ((item.transform[4]-lastXIndent)/lastXIndent > .05) { //if the x position has increased significantly, assume it's a new paragraph
              isNewParagraph = true;
            }
            else {
              lastXIndent = item.transform[4]; //only update lastXIndent if we are not starting a new paragraph, to allow for multiple lines of the same paragraph to have slightly different indents without breaking the paragraph
            }

          
            //if the last line was displayed as a page number then treat this line as a new paragraph, and reset the state keeping track of whether the last line was a page number
            if (lastLineWasPageNumber) {
              isNewParagraph = true
              lastLineWasPageNumber = false
            }
            //if this is not a new paragraph and the height is the same as the previous item, assume it's a continuation of the same line and concatenate the text
            if (!isNewParagraph && i > 0 && headingLevel == tempDocText[tempDocText.length-1].headingLevel) {

              //if the last character of the last line is a "-" then remove it before combining (since a word was likely broken across two lines)
              let lastLine = tempDocText[tempDocText.length - 1].text;
              if (lastLine[lastLine.length-1] === "-") {
                lastLine = lastLine.slice(0, -1);
                tempDocText[tempDocText.length - 1].text = lastLine + lineText; //also combine the lines wihtout adding a space (in the middle of a word)
              }
              else {
                tempDocText[tempDocText.length - 1].text += " " + lineText;
              }
              
            }
            else {
              //otherwise add the text and the corresponding heading level to tempDocText with yPos
              const adjustedYPos = calculateAdjustedYPos(pageHeight, item.transform[5], pageStartYPos);
              tempDocText.push({"text": lineText, "headingLevel": headingLevel, "yPos": adjustedYPos});
              
            }
          }

          //now try to extract images from this page
          try {
            const extractedImages = await extractImages(pdf, pageNum+1); //unPDF page numbers are 1-indexed
            console.log("Found " + extractedImages.length + " images on page " + (pageNum+1));

            for (const imgObj of extractedImages) {
              const canvas = document.createElement('canvas');
              const context = canvas.getContext('2d');
              
              if (!context) continue;

              canvas.width = imgObj.width;
              canvas.height = imgObj.height;

              //create ImageData from the extracted image data
              const imageData = context.createImageData(imgObj.width, imgObj.height);
              imageData.data.set(imgObj.data);
              
              //put the image data on the canvas
              context.putImageData(imageData, 0, 0);

              //convert canvas to data URL
              const imageDataUrl = canvas.toDataURL('image/png');
              
              //add the extracted image to docElements
              //use a large negative yPos to place it with the text from the same page
              docElements.push({
                type: 'image',
                src: imageDataUrl,
                yPos: pageStartYPos
              });
            }
          } catch (err) {
            console.warn(`Failed to extract images from page ${pageNum}:`, err);
          }

        }

        //convert tempDocText to docElements
        for (let textItem of tempDocText) {
          docElements.push({
            type: 'text',
            text: textItem.text,
            headingLevel: textItem.headingLevel,
            yPos: textItem.yPos
          });
        }

        console.log(docElements);

        //const { totalPages, text } = await extractText(pdf, {mergePages: true});




        if (cancelled) return;

        //sort docElements by yPos (in accending order, then by type to keep images together)
        docElements.sort((a, b) => {
          if (a.yPos !== b.yPos) return a.yPos - b.yPos;
          return a.type === 'image' ? 1 : -1;
        });

        const elements = docElements.map((element, idx) => {
          if (element.type === 'text') {
            return (
              <PdfReadableLine 
                key={idx} 
                headingLevel={element.headingLevel} 
                content={element.text} 
                defaultToSummary={settings.AIDefaultShortening}
                textColor={settings.textColor}
                minLengthToSummarize={settings.minLengthToSummarize}
                summarizePercent={settings.targetSummaryLength}
              />
            );
          } else {
            return (
              <PdfImageLine 
                key={idx} 
                src={element.src}
              />
            );
          }
        });

        if (!cancelled && mounted.current) setReadableHtml(elements);
      } catch (err: any) {
        if (!cancelled && mounted.current) setError(String(err.message ?? err));
      } finally {
        if (!cancelled && mounted.current) setLoading(false);
      }
    }

    processPdf();

    return () => {
      cancelled = true;
    };
  }, [file]);


  const styleDictBackground = {
    backgroundColor: settings.backgroundColor
  }
  const styleDictTextColor = {
    color: settings.textColor
  }
  return (
    <>
      <Header />
      <main className="min-h-screen p-8" style={styleDictBackground}>
        <h1 className="text-3xl text-gray-600" style={styleDictTextColor}>PDF Reading</h1>
        <a href="pdf-reading-settings" style={styleDictTextColor}>PDF Reader Settings</a>
        <div className="mt-6">
          <label className="block text-sm font-medium text-gray-700" style={styleDictTextColor}>Upload a PDF using the browse button below then the text content will appear below</label>
          <input
            type="file"
            accept="application/pdf,.pdf"
            onChange={handleFileChange}
            className="mt-2"
            style={styleDictTextColor}
          />
          {fileName && <p className="mt-2 text-sm text-gray-500" style={styleDictTextColor}>Selected: {fileName}</p>}
        </div>

        <div className="mt-6 grid grid-cols-1 md:grid-cols-1 gap-6">
          <div>
              <div>
                <h2 className="text-lg font-medium mb-2" style={styleDictTextColor}>Output</h2>
                
                  {loading && <p className="text-sm text-gray-500" style={styleDictTextColor}>Processing PDF...</p>}
                  {error && <p className="text-sm text-red-500" style={styleDictTextColor}>Error: {error}</p>}
                  {!loading && !error && readableHtml && (
                    <div className="border rounded p-4 bg-white h-fit-content w-full" style={styleDictBackground}>
                      <p style={styleDictTextColor}>Below is the content of the document. When you select a button labeled summarize line? you can press the button to toggle an AI shortened version of the following line or paragraph. Pressing the button again will return the original version.</p>
                      <div>{readableHtml}</div>
                    </div>
                  )}
                  {!loading && !error && !readableHtml && (
                    <p className="text-sm text-gray-500" style={styleDictTextColor}>Once you upload a PDF using the browse button above, the text content of the document will appear here</p>
                  )}
                
              </div>
            </div>
          </div>
      </main>
    </>
  );
}

function escapeHtml(str: string) {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/\"/g, "&quot;")
    .replace(/'/g, "&#039;");
}

// Client helper: shorten a paragraph by a given percent using the InsForge model gateway
// `percent` is the percentage to shorten by (e.g. 30 means reduce length by 30%)
export async function shortenWithInsforge(text: string, percent: number) {
  const res = await fetch("/api/insforge/shorten", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ text, percent }),
  });
  if (!res.ok) {
    const body = await res.text();
    throw new Error(body || "Request failed");
  }
  const json = await res.json();
  return json.shortened as string;
}

//This function was written by GPT-5 mini
// Accepts values up to 3999 (standard Roman numeral form).
export function parseRomanNumeral(input: string): number {
  if (typeof input !== "string") return NaN;
  const s = input.trim().toUpperCase();
  if (s.length === 0) return NaN;

  // Strict validation for standard Roman numerals (0-3999)
  const valid = /^M{0,3}(CM|CD|D?C{0,3})(XC|XL|L?X{0,3})(IX|IV|V?I{0,3})$/;
  if (!valid.test(s)) return NaN;

  const map: Record<string, number> = { I: 1, V: 5, X: 10, L: 50, C: 100, D: 500, M: 1000 };
  let total = 0;
  for (let i = 0; i < s.length; i++) {
    const value = map[s[i]];
    const next = map[s[i + 1]] ?? 0;
    if (value < next) total -= value;
    else total += value;
  }
  return total;
}

//when repeatedly caled with the y information extracted from a pdf about the location of text elements this function will adjust the y values so they are always increasing when an element is lower in a document.
function calculateAdjustedYPos(pageHeight: number, originalYTransform: number, pageStartYPos: number) {
  
  return (pageHeight - originalYTransform) + pageStartYPos;
}

