"use client"

//notes about this file
//This file was written mostly by GPT-5 mini with some parts written by Daniel Briggs

import React, { useEffect, useRef, useState } from "react";
import { Header } from "@/components/layout";
import { Readability } from "@mozilla/readability";
import DOMPurify from "dompurify";
import { getResolvedPDFJS, extractText, getDocumentProxy } from 'unpdf';
import type { TextItem, TextContent } from 'pdfjs-dist/types/src/display/api';



export default function Page() {
  const [file, setFile] = useState<File | null>(null);
  const [fileName, setFileName] = useState<string | null>(null);
  const [readableHtml, setReadableHtml] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const mounted = useRef(true);




  //USER SETTINGS
  let displayPageNumbers = false;







  useEffect(() => {
    mounted.current = true;
    return () => {
      mounted.current = false;
    };
  }, []);

  async function handleFileChange(e: React.ChangeEvent<HTMLInputElement>) {
    const f = e.target.files?.[0] ?? null;
    if (!f) return;
    const isPdf = f.type === "application/pdf" || f.name.toLowerCase().endsWith(".pdf");
    if (!isPdf) {
      alert("Please upload a PDF file.");
      e.currentTarget.value = "";
      setFile(null);
      setFileName(null);
      return;
    }
    setFile(f);
    setFileName(f.name);
    setReadableHtml(null);
    setError(null);
  }

  useEffect(() => {
    if (!file) return;
    let cancelled = false;

    async function processPdf() {
      setLoading(true);
      setError(null);


      try {
       
        
        if (file == null) throw new Error("No file to process");
        const arrayBuffer = await file.arrayBuffer();

        let fullText = "";
        const pdf = await getDocumentProxy(new Uint8Array(arrayBuffer));
        console.log(await pdf.numPages);
        const pdfJS = await getResolvedPDFJS(); //get direct access to the underlying PDF.js library used by unpdf
        
        //load list of all pages
        let listOfPagePromises = [];
        for (let i = 1; i <= pdf.numPages; i++) {
          listOfPagePromises.push(pdf.getPage(i));
        }
        const pages = await Promise.all(listOfPagePromises);
        

        //for each page extract the textContent elements
        let textContents : TextItem[] = [] ;
        for (let page of pages) {
          const textContent : TextContent = await page.getTextContent({includeMarkedContent: false}); //get the list of TextContent objects without any TextMarkedContentObjects
          let textContentItems = textContent.items as TextItem[];
          textContents.push(...textContentItems); //ignore the styles and lang properties of each TextContent object
        }

        //build a list containing all the pdf from the pdf with the relative text sizes
        let docText: { text: string; headingLevel: number }[] = [];

        //create a list of all the text heights in the document to sort by
        let heights : number[] = [];
        for (let item of textContents) {
          if (!heights.includes(item.height)) {
            heights.push(item.height);
          }
        }
        heights.sort((a,b) => b-a); //sort heights from largest to smallest

        //The following conversion from heights to headings was generated by GPT-5 mini
        // Create a dictionary mapping each unique height to an estimated heading level (1..6)
        // Largest height -> 1 (h1), smallest -> 6 (h6). Heights in between are scaled.
        const heightToHeading: Record<number, number> = {};
        if (heights.length === 1) {
          heightToHeading[heights[0]] = 1;
        } else if (heights.length > 1) {
          const maxIndex = heights.length - 1;
          for (let i = 0; i < heights.length; i++) {
            const rank = i; // 0 = largest, maxIndex = smallest
            const level = Math.min(6, Math.max(1, Math.round((rank / maxIndex) * 5) + 1));
            heightToHeading[heights[i]] = level;
          }
        }
        console.log("textContent: ");
        console.log(textContents);
        

        let lastXIndent = -999;
        //populate docText as a simplified version of textContents (only the text and height properties)
        for (let i = 0; i < textContents.length; i++) {
          const item = textContents[i] as TextItem;
          let lineText = item.str;

          //if the text is empty or only whitespace, skip it
          if (lineText.trim() === "") continue;

          //check whether this is a new page
          let newPage = false;
          if (i == 0) {
            newPage = true;
          }
          else if (item.transform[5] > textContents[i-1].transform[5]) { //if the y position has increased, it's a new page
            newPage = true;
          }

          //check the heading level
          const headingLevel = heightToHeading[item.height] || 6; //default to 6 if height not recognized
          

          //if it's a new page then check whether this line or the last line is likely a page number and reformat it
          if (newPage) {
            //check whether the lineText is a arabic or roman numeral
            let pageNum = Number(lineText.trim());
            if (isNaN(pageNum)) {
              //try parsing as a roman numeral
              pageNum = parseRomanNumeral(lineText.trim());
              if (isNaN(pageNum)) {
                //probably not a page num
              }
            }

            //if the lineText is likely a page number, reformat it to "Page X"
            if (!isNaN(pageNum)) {
              lineText = "Page " + pageNum;

              if (displayPageNumbers) {
                docText.push({"text": lineText, "headingLevel": headingLevel});
              }
              continue; //skip the other parsing logic for this line
            }
          }

          //check whether this is the start of a new paragraph
          let isNewParagraph = false;
          if ((item.transform[4]-lastXIndent)/lastXIndent > .05) { //if the x position has increased significantly, assume it's a new paragraph
            isNewParagraph = true;
          }
          else {
            lastXIndent = item.transform[4]; //only update lastXIndent if we are not starting a new paragraph, to allow for multiple lines of the same paragraph to have slightly different indents without breaking the paragraph
          }

          

          //if this is not a new paragraph and the height is the same as the previous item, assume it's a continuation of the same line and concatenate the text
          if (!isNewParagraph && i > 0 && headingLevel == docText[docText.length-1].headingLevel) {

            //if the last character of the last line is a "-" then remove it before combining (since a word was likely broken across two lines)
            let lastLine = docText[docText.length - 1].text;
            if (lastLine[lastLine.length-1] === "-") {
              lastLine = lastLine.slice(0, -1);
              docText[docText.length - 1].text = lastLine + lineText; //also combine the lines wihtout adding a space (in the middle of a word)
            }
            else {
              docText[docText.length - 1].text += " " + lineText;
            }
            
          }
          else {
            //otherwise add the text and the corresponding heading level to docText
            docText.push({"text": lineText, "headingLevel": headingLevel});
          }
        }


        console.log(docText)

        //const { totalPages, text } = await extractText(pdf, {mergePages: true});




        if (cancelled) return;

        // Build a minimal HTML document for Readability
        const bodyHtml = docText
          .map((line) => {
            switch (line.headingLevel) {
              case 1: return '<p class="text-2xl font-bold mt-4 mb-2">' + escapeHtml(line.text) + '</p>';
              case 2: return '<p class="text-xl font-bold mt-3 mb-1.5">' + escapeHtml(line.text) + '</p>';
              case 3: return '<p class="text-lg mt-2 mb-1">' + escapeHtml(line.text) + '</p>';
              case 4: return '<p class="text-md mt-1.5 mb-1">' + escapeHtml(line.text) + '</p>';
              case 5: return '<p class="text-base mt-1 mb-0.5">' + escapeHtml(line.text) + '</p>';
              case 6: return '<p class="text-sm mt-1 mb-0.5">' + escapeHtml(line.text) + '</p>';
              default:
                console.log("invalid heading level: " + line.headingLevel);
                return '<p>' + escapeHtml(line.text) + '</p>';
              
            }
        })
        console.log("bodyHtml: " + bodyHtml);
          
        const docHtml = `<!doctype html><html><head><meta charset=\"utf-8\"></head><body><article>${bodyHtml.join("")}</article></body></html>`;

        // Sanitize before parsing into DOM
        const sanitized = DOMPurify.sanitize(docHtml);
        const parser = new DOMParser();
        const doc = parser.parseFromString(sanitized, "text/html");

        // send html through Readability Library
        //const reader = new Readability(doc);
        //const article = reader.parse();
        //const content = article?.content ?? `<p>No readable content could be extracted.</p>`;

        const final = DOMPurify.sanitize(docHtml);
        if (!cancelled && mounted.current) setReadableHtml(final);
      } catch (err: any) {
        if (!cancelled && mounted.current) setError(String(err.message ?? err));
      } finally {
        if (!cancelled && mounted.current) setLoading(false);
      }
    }

    processPdf();

    return () => {
      cancelled = true;
    };
  }, [file]);

  return (
    <>
      <Header />
      <main className="min-h-screen p-8">
        <h1 className="text-3xl text-gray-600">PDF Reading</h1>

        <div className="mt-6">
          <label className="block text-sm font-medium text-gray-700">Upload PDF</label>
          <input
            type="file"
            accept="application/pdf,.pdf"
            onChange={handleFileChange}
            className="mt-2"
          />
          {fileName && <p className="mt-2 text-sm text-gray-500">Selected: {fileName}</p>}
        </div>

        <div className="mt-6 grid grid-cols-1 md:grid-cols-2 gap-6">
          <div>
            <h2 className="text-lg font-medium mb-2">Preview</h2>
              <div>
                <h2 className="text-lg font-medium mb-2">Readability Output</h2>
                <div className="border rounded p-4 h-[600px] overflow-auto bg-white">
                  {loading && <p className="text-sm text-gray-500">Processing PDF...</p>}
                  {error && <p className="text-sm text-red-500">Error: {error}</p>}
                  {!loading && !error && readableHtml && (
                    <div dangerouslySetInnerHTML={{ __html: readableHtml }} />
                  )}
                  {!loading && !error && !readableHtml && (
                    <p className="text-sm text-gray-500">Upload a PDF to extract readable content.</p>
                  )}
                </div>
              </div>
            </div>
          </div>
      </main>
    </>
  );
}

function escapeHtml(str: string) {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/\"/g, "&quot;")
    .replace(/'/g, "&#039;");
}

// Client helper: shorten a paragraph by a given percent using the InsForge model gateway
// `percent` is the percentage to shorten by (e.g. 30 means reduce length by 30%)
export async function shortenWithInsforge(text: string, percent: number) {
  const res = await fetch("/api/insforge/shorten", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ text, percent }),
  });
  if (!res.ok) {
    const body = await res.text();
    throw new Error(body || "Request failed");
  }
  const json = await res.json();
  return json.shortened as string;
}

//This function was written by GPT-5 mini
// Accepts values up to 3999 (standard Roman numeral form).
export function parseRomanNumeral(input: string): number {
  if (typeof input !== "string") return NaN;
  const s = input.trim().toUpperCase();
  if (s.length === 0) return NaN;

  // Strict validation for standard Roman numerals (0-3999)
  const valid = /^M{0,3}(CM|CD|D?C{0,3})(XC|XL|L?X{0,3})(IX|IV|V?I{0,3})$/;
  if (!valid.test(s)) return NaN;

  const map: Record<string, number> = { I: 1, V: 5, X: 10, L: 50, C: 100, D: 500, M: 1000 };
  let total = 0;
  for (let i = 0; i < s.length; i++) {
    const value = map[s[i]];
    const next = map[s[i + 1]] ?? 0;
    if (value < next) total -= value;
    else total += value;
  }
  return total;
}
